---
title: "spider_charts"
author: "David Ibañez"
date: "6 de agosto de 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
#Inicializaci?n del proyecto
set.seed(123)
rm(list = ls())
options(scipen=999)
if (!require("pacman")) install.packages("pacman")
pacman::p_load("openxlsx", "data.table", "ggplot2", "fmsb")
```

```{r include=FALSE}
datos <- fread("data/country_data.csv")
head(datos)
```
```{r include=FALSE}
sapply(datos, class)
unique(datos$incomelevel)
level_income <-  c("Low income",  "Lower middle income", "Upper middle income",  "High income: OECD",    "High income: nonOECD")
datos[, incomelevel := factor(incomelevel, levels = level_income, ordered = T)]
levels(datos$incomelevel)
```
```{r include=FALSE}
datos[, incomelevel := as.numeric(incomelevel)]
max(datos$incomelevel)
```

```{r include=FALSE}
indicators <- c( "Sovereignty_Index", "Political_System_Index", "Globalization_Index", "Growth_GDP")
countries <- unique(datos$wb_name)

#### MAXIMUN AN MINIMUN INDICATORS USING ALL COUNTRIES ####
max_indicator <- datos[, lapply(.SD, max ), .SDcols = indicators]
min_indicator <- datos[, lapply(.SD, min ), .SDcols = indicators]
max_indicator
min_indicator
```
```{r include=FALSE}
datos[, lapply(.SD, function(x){seq(min(x),max(x),length.out = 5)}), .SDcols = indicators]
sovereignty_levels <- seq(min(datos$Sovereignty_Index),max(datos$Sovereignty_Index),length.out = 5)
```
# Spider charts 
```{r echo=FALSE}
# Color vector
colors_border=c( rgb(0,0.0,0.3,0.9), rgb(0.8,0.2,0.5,0.9) , rgb(0.7,0.5,0.1,0.9), rgb(0.2,0.5,0.5,0.9)   )
colors_in=c( rgb(0,0.0,0.3,0.2) , rgb(0.8,0.2,0.5,0.2) , rgb(0.7,0.5,0.1,0.2), rgb(0.2,0.5,0.5,0.2))
i = 1
for(i in 1:length(countries)){
  plot_data <- datos[wb_name == countries[i]]
  years <-  unique(plot_data$year)
  #### MAXIMUN AN MINIMUN INDICATORS USING ONLY CONTRY i ####
  # max_indicator <- plot_data[, lapply(.SD, max ), .SDcols = indicators]
  # min_indicator <- plot_data[, lapply(.SD, min ), .SDcols = indicators]
  plot_data <- rbindlist(list(max_indicator, min_indicator, plot_data[, mget(indicators)]))
  plot_data <- data.frame(plot_data)
  rownames(plot_data) <- c("1", "2", years)
  colnames(plot_data) <- c( "Sovereignty \n Index", "Political \n System Index", "Globalization \n Index", "Growth \n GDP")
    
    # plot with default options:
  radarchart(
    plot_data  ,
    axistype = 1 ,
    #custom polygon
    pcol = colors_border ,
    pfcol = colors_in ,
    plwd = 3 ,
    plty = 1,
    #custom the grid
    cglcol = "grey",
    cglty = 1,
    axislabcol = "grey",
    caxislabels = sovereignty_levels,
    cglwd = 0.8,
    #custom labels
    vlcex = 0.8,
    title = paste0(countries[i], "'s analysis")
    )
  
  # Add a legend
  legend(
    x = 1.5,
    y = 0,
    legend = rownames(plot_data[-c(1, 2), ]),
    bty = "n",
    pch = 20 ,
    col = colors_in ,
    text.col = "grey",
    cex = 1.2,
    pt.cex = 3
    )


}


```










